services:
  backend:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build:
      context: ./BankAppWebAPI
      dockerfile: /BankAppWebAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Bangkok

  frontend:
    build:
      context: ./bankapplication
      dockerfile: /Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://backend:8081
    depends_on:
      - backend
